### ISSUE TITLE
opening a file with synth plugin fails to route

### ISSUE THREAD

**Issue by ccherrett** [ccherrett/oom#72] opened 2012-02-15 08:29 UTC
Opening a file with synth plugin fails to route in some situations and you get no audio

Open a file like this:

oomidi yourmidifile.oom

This with throw an error like this:

jack connect OOMidi:Master-10x56918d0 - OOMidi:iorgan-00x5483700 failed with err:17

I also got this error when doing an open with recent project

Route::read(): jack port OOMidi:O-organ:out_r not found Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1

**Comment by ccherrett** [comment] 2012-02-26 17:50
Route::read(): jack port OOMidi:O-TAL NoiseMaker Plugin [VST]:output_1 not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1
Route::read(): jack port OOMidi:O-TAL NoiseMaker Plugin [VST]:output_2 not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1
Route::read(): jack port OOMidi:O-String [VST]:output_1> not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1
Route::read(): jack port OOMidi:O-String [VST]:output_2> not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1
Route::read(): jack port OOMidi:O-Calf Organ [LV2]:out_l not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1
Route::read(): jack port OOMidi:O-Calf Organ [LV2]:out_r not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1
Route::read(): jack port OOMidi:O-Calf Monosynth [LV2]:out_l not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1
Route::read(): jack port OOMidi:O-Calf Monosynth [LV2]:out_r not found
  Warning - route invalid. Ignoring route! srcValid: 0, destValid: 1

**Comment by ccherrett** [comment] 2012-02-26 18:17
http://www.openoctave.org/synth_routing_bug.png

when trying to reopen the project the synths ports are being renamed with an _1. We think it is a race condition. Jack sees a port with this name already and renames it for you.

Will get fixed soon.

**Comment by linuxras** [comment] 2012-03-03 06:57
I think the earlier versions of this bug was fixed, the remaining I could only reproduce with open recent or opening the same project as the current.

This was caused by the synth device closing but not being removed from the internal midiDevices list.

Fixed until someone can reproduce it again.

**Closed as completed by linuxras** 2012-03-03 06:57 UTC
